# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mtibben/percent
%global goipath         github.com/mtibben/percent
Version:                0.2.1

%gometa

%global common_description %{expand:
Package percent escapes strings using percent-encoding.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package percent escapes strings using percent-encoding

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Nov 24 21:10:01 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 0.2.1-1
- Initial package

