# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mattn/go-runewidth
%global goipath         github.com/mattn/go-runewidth
Version:                0.0.10

%gometa

%global common_description %{expand:
Wcwidth for golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Wcwidth for golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/rivo/uniseg)

%description
%{common_description}

%gopkg

%prep
%goprep


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md

%gopkgfiles

%changelog
* Wed Mar 24 21:07:54 CET 2021 SoMuchForSubtlety <jakob@ahrer.dev> - 0.0.10-1
- Initial package

