# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/SoMuchForSubtlety/keyring
%global goipath         github.com/SoMuchForSubtlety/keyring
Version:                1.1.6

%gometa

%global common_description %{expand:
Go library providing a uniform interface across a range of secure credential
stores.}

%global golicenses      LICENSE
%global godocs          README.md vagrant/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library providing a uniform interface across a range of secure credential stores

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/dvsekhvalnov/jose2go)
BuildRequires:  golang(github.com/godbus/dbus)
BuildRequires:  golang(github.com/gsterjov/go-libsecret)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mtibben/percent)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md vagrant/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Nov 24 20:34:12 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 1.1.6-1
- Initial package

