# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/gdamore/tcell
%global goipath         github.com/gdamore/tcell/v2
Version:                2.1.0

%gometa

%global common_description %{expand:
Tcell is an alternate terminal package, similar in some ways to termbox, but
better in others.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.adoc terminfo/README.md\\\
                        terminfo/TERMINALS.md terminfo/models.txt\\\
                        views/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Tcell is an alternate terminal package, similar in some ways to termbox, but better in others

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/encoding)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/text/encoding)
BuildRequires:  golang(golang.org/x/text/encoding/charmap)
BuildRequires:  golang(golang.org/x/text/encoding/japanese)
BuildRequires:  golang(golang.org/x/text/encoding/korean)
BuildRequires:  golang(golang.org/x/text/encoding/simplifiedchinese)
BuildRequires:  golang(golang.org/x/text/encoding/traditionalchinese)
BuildRequires:  golang(golang.org/x/text/transform)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS README.adoc terminfo/README.md terminfo/TERMINALS.md
%doc terminfo/models.txt views/README.md

%gopkgfiles

%changelog
* Sat Feb 13 23:54:26 CET 2021 SoMuchForSubtlety <jakob@ahrer.dev> - 2.1.0-1
- upgrade to 2.1.0
* Tue Nov 25 12:02:35 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 2.0.0-4
- try to fix version
* Tue Nov 24 22:39:48 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 2.0.0-3
- Use v2
* Tue Nov 24 21:15:45 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 2.0.0-2
- Don't build demos
* Tue Nov 24 20:33:09 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 2.0.0-1
- Initial package

