# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/rivo/tview
%global goipath         github.com/rivo/tview
%global commit          dbc1f32bb1d02db2f8c497700b7db237362d4ff8

%gometa

%global common_description %{expand:
Rich interactive widgets for your terminal UI, written in Go.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Rich interactive widgets for your terminal UI, written in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/rivo/uniseg)

%description
%{common_description}

%gopkg

%prep
%goprep


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

%gopkgfiles

%changelog
* Sun Feb 14 00:13:27 CET 2021 SoMuchForSubtlety <jakob@ahrer.dev> - 0-0.1.20210214gitdbc1f32
- Upgrade to latest commit 
* Tue Nov 24 22:12:40 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 0-0.2.20201124gitf007e9a
- Fix tcell dependency
* Tue Nov 24 20:32:42 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 0-0.1.20201124gitf007e9a
- Initial package

