# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/rivo/uniseg
%global goipath         github.com/rivo/uniseg
Version:                0.2.0

%gometa

%global common_description %{expand:
Unicode Text Segmentation for Go (or: How to Count Characters in a String).}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Unicode Text Segmentation for Go (or: How to Count Characters in a String)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Nov 24 22:20:23 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 0.2.0-1
- Initial package

