# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/SoMuchForSubtlety/tview
%global goipath         github.com/SoMuchForSubtlety/tview
%global commit          c4de038979df4f0c2f1891d71511b37cbb703bd3

%gometa

%global common_description %{expand:
Rich interactive widgets for terminal-based UIs written in Go.}

%global golicenses      LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Rich interactive widgets for terminal-based UIs written in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/rivo/tview)
BuildRequires:  golang(github.com/rivo/uniseg)

%description
%{common_description}

%gopkg

%prep
%goprep


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

%gopkgfiles

%changelog
* Wed Mar 24 20:25:55 CET 2021 SoMuchForSubtlety <jakob@ahrer.dev> - 0-0.1.20210324gitc4de038
- Initial package

