# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/rivo/tview
%global goipath         github.com/rivo/tview
%global commit          f007e9ad3893af1068c32017864c9b50bef38c1b

%gometa

%global common_description %{expand:
Rich interactive widgets for terminal-based UIs written in Go.}

%global golicenses      LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        demos/box/README.md demos/button/README.md\\\
                        demos/checkbox/README.md demos/dropdown/README.md\\\
                        demos/flex/README.md demos/form/README.md\\\
                        demos/frame/README.md demos/grid/README.md\\\
                        demos/inputfield/README.md demos/list/README.md\\\
                        demos/modal/README.md demos/pages/README.md\\\
                        demos/primitive/README.md demos/table/README.md\\\
                        demos/textview/README.md demos/treeview/README.md\\\
                        demos/unicode/README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Rich interactive widgets for terminal-based UIs written in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gdamore/tcell/v2)
BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/rivo/uniseg)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in demos/unicode demos/checkbox demos/treeview demos/box demos/flex demos/textview demos/button demos/list demos/frame demos/grid demos/inputfield/autocompleteasync demos/dropdown demos/table demos/inputfield/autocomplete demos/pages demos/form demos/inputfield demos/modal demos/primitive demos/presentation; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md demos/box/README.md
%doc demos/button/README.md demos/checkbox/README.md demos/dropdown/README.md
%doc demos/flex/README.md demos/form/README.md demos/frame/README.md
%doc demos/grid/README.md demos/inputfield/README.md demos/list/README.md
%doc demos/modal/README.md demos/pages/README.md demos/primitive/README.md
%doc demos/table/README.md demos/textview/README.md demos/treeview/README.md
%doc demos/unicode/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Nov 24 20:32:42 CET 2020 SoMuchForSubtlety <jakob@ahrer.dev> - 0-0.1.20201124gitf007e9a
- Initial package

